apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: madgraph
spec:
  selector:
    matchLabels:
      name: madgraph
  template:
    metadata:
      labels:
        name: madgraph
    spec:
      nodeSelector:
        node-role.kubernetes.io/gpu: "true"
# uncomment to run on GCP
#        tolerations:
#        - key: "nvidia.com/gpu"
#          operator: "Equal"
#          value: "present"
#          effect: "NoSchedule"
      containers:
      - name: madgraph
        image: "gitlab-registry.cern.ch/cloud/atomic-system-containers/madgraph4gpu"
        imagePullPolicy: Always
        command: ["/bin/bash", "-c", "while true; do ./gcheck.exe -p 4096 32 64 | egrep -A2 'TotalEventsComputed'; done"]
        resources:
          limits:
            nvidia.com/gpu: 1
        securityContext:
          privileged: true
# useful to run at CERN, but the latest image should contain the drivers
#        env:
#          - name: PATH
#            value: "/bin:/usr/bin:/usr/local/bin:/opt/nvidia-driver/bin"
#          - name: LD_LIBRARY_PATH
#            value: "/opt/nvidia-driver/lib64"
#        volumeMounts:
#          - name: nvidia-driver
#            mountPath: /opt/nvidia-driver
#      volumes:
#      - name: nvidia-driver
#        hostPath:
#          path: /opt/nvidia-driver
